server:
  port: 8080

spring:
  application:
    name: apigw
  config:
    import: "configserver:http://localhost:8888"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/