server:
  port: 8080

spring:
  application:
    name: apigw
  cloud:
    gateway:
      routes:
        - id: productService
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: orderService
          uri: lb://order-service
          predicates:
            - Path=/order/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/