spring:
  cloud:
    gateway:
      routes:
        - id: productService
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: orderService
          uri: lb://order-service
          predicates:
            - Path=/order/**