server.port: 8082

spring:
  application.name: order-service
  config:
    import: "configserver:http://localhost:8888"

security:
  oauth2:
    client:
      client-id: order-service
      client-secret: pwd-order-service
      scope: read
      grant-type: client_credentials, password
      access-token-uri: http://localhost:9090/oauth/token
    resource:
      token-info-uri: http://localhost:9090/oauth/check_token
