server.port: 9090

spring:
  application.name: authentication-server
  config:
    import: "configserver:http://localhost:8888"
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  security:
    jwt:
      private-key: asd123
      public-key: '-----BEGIN PUBLIC KEY-----\ntadadada\n-----END PUBLIC KEY-----'

logging:
  level:
    org.springframework: DEBUG