server.port: 8888
spring:
  application.name: config-server
  cloud.config.server.git:
    uri: file://Users/ahulger/dev-env/repositories/me/microservices-cloud/config-repo
    searchPaths: '{application}'
    default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/